FROM node:20-alpine

WORKDIR /app

COPY package.json ./
COPY pnpm-lock.yaml ./
COPY pnpm-workspace.yaml ./
COPY turbo.json ./

RUN npm install -g pnpm
COPY ./packages ./packages
COPY ./apps/web ./apps/web

RUN pnpm install

RUN pnpm build

EXPOSE 3000

CMD ["pnpm" , "start:web"]