FROM node:20-alpine

WORKDIR /app

COPY package.json ./
COPY pnpm-lock.yaml ./
COPY pnpm-workspace.yaml ./
COPY turbo.json ./

RUN npm install -g pnpm
COPY ./packages ./packages
COPY ./apps/web ./apps/web

RUN pnpm install

WORKDIR /app/apps/web
ARG NEXT_PUBLIC_WS_URL
ENV NEXT_PUBLIC_WS_URL=$NEXT_PUBLIC_WS_URL

RUN pnpm build

EXPOSE 3000

CMD ["pnpm" , "start"]