name: Deployment of websocket to vps
on:
    push:
        branches: [ prod ]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -
                name: checkout the code
                uses: actions/checkout@v2

            -
                name: Docker login
                uses: docker/login-action@v2
                with:
                    username: ${{ secrets.DOCKERHUB_USERNAME }}
                    password: ${{ secrets.DOCKERHUB_TOKEN }}
            -
                name: Build and push
                uses: docker/build-push-action@v4
                with:
                    file: ./docker/Dockerfile.ws
                    push: true
                    tags: techindustry/point8factor-ws:${{ github.sha }}
